### ISSUE TITLE
The requested captchaStyle 'yourFirstCaptchaStyle' is not defined in the botdetect.xml!

### ISSUE THREAD

**Issue by ibtissambth** [captcha-com/angular-captcha#7]
Hey, I use angular-captcha with angular frontend and spring backend.
I did all the steps defined in [https://captcha.com/angular-captcha.html#angular-java-spring-backend:springboot-autoconfiguration](url) but when I call [my-api-endpoint/simple-captcha-endpoint?get=html&c=yourFirstCaptchaStyle](url) its gives me the followeing error 

`{
    "timestamp": "2021-02-08T00:37:14.011+0000",
    "status": 400,
    "error": "Bad Request",
    "message": "The requested captchaStyle 'yourFirstCaptchaStyle' is not defined in the botdetect.xml!",
    "path": "//simple-captcha-endpoint"
}`

here is my botdetect.xml file content : 
`<?xml version="1." encodi0ng="UTF-8"?>`
`<botdetect xmlns="https://captcha.com/schema/java"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="https://captcha.com/schema/java
             https://captcha.com/schema/java/botdetect-4.0.beta3.7.xsd">
    <captchaStyles>
        <captchaStyle>
            <name>yourFirstCaptchaStyle</name>
            <userInputID>yourFirstCaptchaUserInput</userInputID>
        </captchaStyle>
    </captchaStyles>
</botdetect>`

did I miss something ? thanks in advance

**Comment by ibtissambth** [comment]
I dont know why I get this error just when working on https domain, but not on http://localhost

**Comment by ibtissambth** [comment]
`"BDC_configFileLocation", "/WEB-INF/classes/botdetect.xml");`

The path **/WEB-INF/classes/botdetect.xml** worked for me

**Comment by botdetect-support** [comment]
Where is botdetect.xml located? In the `/WEB-INF/ `folder of your app,
or in the `/resources/` folder?

If it is in `/WEB-INF/ `folder, please try to move it to `/resources/`
folder, and configure the path to `botdetect.xml` in the following way:

```java
@SpringBootApplication
public class YourAppBackend {

    [...]

    @Bean
    public ServletContextInitializer initializer() {
        return new ServletContextInitializer() {

            @Override
            public void onStartup(ServletContext servletContext) throws ServletException {
                servletContext.setInitParameter(
                    "BDC_configFileLocation", "/resources/botdetect.xml");
            }
        }
    }
}
```

Hope this helps.
